services:
  web:
    build: .
    # user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "5000:9000"
    volumes:
      - .:/app
      - db_data:/app/pokemon-project/data/
    env_file:
      - pokemon-project/.env
    stdin_open: true
    tty: true
    depends_on:
      - redis
    command: bash

  redis:
    image: redis:7.2-alpine@sha256:dfa18828cbc07b3ae6a95ec7343f6c214fdee2d836197b4be8e9904420762cd8
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
