services:
  web:
    build: .
    # user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "5000:9000"
    volumes:
      - .:/app
    env_file:
      - pokemon-project/.env
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - db
    command: bash

  redis:
    image: redis:7.2-alpine@sha256:dfa18828cbc07b3ae6a95ec7343f6c214fdee2d836197b4be8e9904420762cd8
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  db:
    image: postgres:17-alpine@sha256:979c4379dd698aba0b890599a6104e082035f98ef31d9b9291ec22f2b13059ca
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  db_data:
  redis_data:
  postgres_data:
