services:
  web:
    build: .
    # user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "5000:9000"
    volumes:
      - .:/app
      - db_data:/app/pokemon-project/data/
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: bash
volumes:
  db_data:
