worker_processes 1; # in production, set to number of available cpu cores or auto to let nginx handle it

events {
    worker_connections 1024; # per worker process, how many simulatenous connections can be opened
}

http {
    upstream pokemontcg_django_app {
        server web:8000;
    }

    server {
        listen 80;
        server_name api.poketcgproject.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name api.poketcgproject.com;

        ssl_certificate /etc/letsencrypt/live/api.poketcgproject.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.poketcgproject.com/privkey.pem;

        # Basic SSL hardening 
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        location / {
            # Pass client information to the backend
            proxy_pass http://pokemontcg_django_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
    }
}
