openapi: 3.0.3
info:
  title: Pokemon TCG Project API
  version: 1.0.0
  description: This is the backend for my pokemon project using Django.
paths:
  /api/authentication/login/:
    post:
      operationId: authentication_login_create
      tags:
      - authentication
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/authentication/register/:
    post:
      operationId: authentication_register_create
      tags:
      - authentication
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/authentication/token/refresh/:
    post:
      operationId: authentication_token_refresh_create
      tags:
      - authentication
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/cards/favorites/:
    get:
      operationId: cards_favorites_retrieve
      tags:
      - cards
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: cards_favorites_create
      tags:
      - cards
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: cards_favorites_destroy
      tags:
      - cards
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/cards/search/:
    get:
      operationId: cards_search_retrieve
      tags:
      - cards
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
