# Generated by Django 5.2.7 on 2026-05-27 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=64)),
                ('card_name', models.CharField(max_length=128)),
                ('card_image', models.CharField(blank=True, default='', max_length=256)),
                ('card_rarity', models.CharField(blank=True, default='', max_length=64)),
                ('card_types', models.CharField(blank=True, default='', max_length=128)),
                ('card_set_id', models.CharField(max_length=64)),
                ('card_set_name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'card_id')},
            },
        ),
    ]
